### PR TITLE
Added intermediate html

### PR DESCRIPTION
**Pull request by Harsh-Singh-Rajput**
# Hackathon Git Labs Project PR 🎉🎉

## PR contains:
- Added intermedite.html and style it using CSS without using any framework
- #69 Solved

## Hacktoberfest 2022:
- [✔ ] Does this PR follow the `intermediate.md` guide and submitted as part of Hacktoberfest 2022?

## Breaking changes
- None

## Screenshots
- Screenshot 1
image
-Screenshot 2
image

- Screenshot 3
image

### CODE REVIEW

**Review by andrewdempsey2018 — CHANGES_REQUESTED** [review]
Hi Harsh, this is fantastic! 🥇  What are your thoughts on having a 'style.css' in the root? I'd recommend renaming it to something more reflective of the fact that it is used in tandem with your 'intermediate.html' file and housing it within the 'CSS' folder to keep the file structure consistent with the rest of the project. @auxfuse I'll watch this one and feel free to chime in if you disagree.

**Comment by auxfuse** [comment]
Hi @andrewdempsey2018 yep, fully agree. If we could use the already defined and in place CSS file and the classes and themes defined in it, that would be great. 😄
Link to current file for reference: https://github.com/auxfuse/hackathon-git-labs/blob/main/assets/css/style.css 

The current file directory for that file is: assets > css > style.css

**Comment by andrewdempsey2018** [comment]
@Harsh-Singh-Rajput So Harsh, as Auxfuse has said, if you could remove the CSS from root and use the file already in place in the CSS folder, that would be great. Regarding the masic.md file -> html, this task has already been picked up by another developer! Take a look at the issues and see if there is something else you'd like to take on!!

**Comment by Harsh-Singh-Rajput** [comment]
> @Harsh-Singh-Rajput So Harsh, as Auxfuse has said, if you could remove the CSS from root and use the file already in place in the CSS folder, that would be great. Regarding the masic.md file -> html, this task has already been picked up by another developer! Take a look at the issues and see if there is something else you'd like to take on!!

@andrewdempsey2018  Ok no issues I will remove the CSS from the root directory and move it to the assets folder and @auxfuse Since there is property which is common to both intermediate and index.html it is not good for adding intermediate css property in style because the index html's css property will also applied to it.
So, we also have to make the changes in index html css by using IDs, so I will use internal css so that no extra file will be created for it

**Comment by Harsh-Singh-Rajput** [comment]
@auxfuse  @andrewdempsey2018 I have made changes please check it

**Comment by auxfuse** [comment]
Hi 👋 @Harsh-Singh-Rajput Thanks for the comments, but I do think we got our wires crossed a bit 😄

What I meant was, we already have a style.css file that powers _all_ of the root project structure. That CSS file is ***the*** file to use. Your embedded CSS is fine for now, and we will approve and merge this. Thanks again for all your hard work on this 🤜 Great PR!

We should have some more Issues added to the project by the end of this week, we would love to see you come back and pick up some more issues and feature tickets in the future.

**Comment by Harsh-Singh-Rajput** [comment]
> Hi 👋 @Harsh-Singh-Rajput Thanks for the comments, but I do think we got our wires crossed a bit 😄
> 
> What I meant was, we already have a style.css file that powers _all_ of the root project structure. That CSS file is _**the**_ file to use. Your embedded CSS is fine for now, and we will approve and merge this. Thanks again for all your hard work on this 🤜 Great PR!
> 
> We should have some more Issues added to the project by the end of this week, we would love to see you come back and pick up some more issues and feature tickets in the future.
Thanks for the appreciation, I will definitely like to work on the upcoming feature/issues. 😀

**Pull request merged**
