### PR TITLE
Random showcase

### PR DESCRIPTION
**Pull request by seanyoung247**
# Hackathon Git Labs Project PR 🎉🎉

A fair few minor code layout changes. I'd noticed that the data can sometimes take a moment to stream in, so I've added some skeleton loaders based on the item templates. Code has been restructured to use a single function to create both community and showcase cards. The changes should make it much easier to paginate the community cards. Which cards are shown can be controlled by an index range. I've moved the custom page flag to a 'showcase' field of the community.json file. I think that would be easier to maintain. I've changed the field generation code in generateCardFromTemplate from if-else's to a object literal, it's a little easier to read and add to I think.

I was hoping to have a unique style for the showcase cards here, but I've tried a couple of different ideas and they didn't really work, and didn't want some of these other changes to get to stale.

## PR contains:
- Adds Skeleton loaders
- Simplifies card generation
- Moves custom page flag to community.json

## Hacktoberfest 2022:
- [x] Does this PR follow the `intermediate.md` guide and submitted as part of Hacktoberfest 2022?

## Breaking changes
- (Should be) none

## Screenshots
image

### CODE REVIEW

**Comment by seanyoung247** [comment]
My current thoughts regarding the showcase styling is to do it as a slide show, but with an iframe showing a scaled version of the custom page instead of a static image. But that's... a bit complex so might take a minute to put together well.

**Review by auxfuse — APPROVED** [review]
The `community.json` file is to be used for complete beginners to the process of version control. It's the only part of the process that I feel we should maintain as simplistically as possible for now.

I'm currently working so that each custom community directory by a Contributor has a `meta.json` file included, with the template as above, and a github action runs on each PR inclusion and then populates that file here, taking the `community.json` file out of the process entirely. I wasn't going to worry about that until after Hacktoberfest, but you do make a valid point in how we identify custom creations. We will approve and merge this for now...and just update the guides to reflect that new boolean. 🤜 Thanks Sean.

**Comment by seanyoung247** [comment]
I've structured the code such that if the showcase field is missing it evaluates to false, so shouldn't effect anything if missing. It's more like an opt in for being added to the showcase section ATM.

**Comment by auxfuse** [comment]
Legend. I did see that, I just mean the less a participant has to do, to just focus on the version control learning, the better 😅 I've seen some people do some incredible things when asked to _not_ worry about a thing. Open source is a strange wonderland! Thanks again Sean, genuinelly impressive stuff man 🤜

**Pull request merged**
