### PR TITLE
Added sidebar component using HTML, CSS

### PR DESCRIPTION
**Pull request by ShubhamGoyal7125**
# Hackathon Git Labs Project PR 🎉🎉

## PR contains:
- I have added sidebar component which can be used in websites and it has sub-navbars also with good UI.
-     {
        "name": "Shubham",
        "course_start": "2020",
        "course_stage": "Student",
        "favorite_language": "JavaScript",
        "currently_learning": "Node.js"
    }
The guide is very easy to read and it is written very well.

## Hacktoberfest 2022:
- [Yes] Does this PR follow the `intermediate.md` guide and submitted as part of Hacktoberfest 2022?

## Breaking changes
- None

## Screenshots
image

### CODE REVIEW

**Comment by ShubhamGoyal7125** [comment]
Please add `hacktoberfest-accepted` label.

**Review by andrewdempsey2018 — COMMENTED** [review]
This is a fine PR but.... @ShubhamGoyal7125 Your personal page does not seem very 'personal'. Do you not want to say something about yourself? @auxfuse Are we OK to allow people free reign on their personal pages? I feel this one is a bit too 'random'. I feel a visitor to the site might get confused if they stumbled on this one

**Comment by auxfuse** [comment]
> This is a fine PR but.... @ShubhamGoyal7125 Your personal page does not seem very 'personal'. Do you not want to say something about yourself? @auxfuse Are we OK to allow people free reign on their personal pages? I feel this one is a bit too 'random'. I feel a visitor to the site might get confused if they stumbled on this one

Hi @andrewdempsey2018 as this the custom creation from the contributor is a sidebar made to showcase their skills, I don't think this is an issue. The site isn't intended for just component creation, but we can of course all this one through, and hope that the original Contributor submits a future PR to make the page more unique to them? What do you think? 😃 I'm happy with your thoughts on it 🤜

**Comment by andrewdempsey2018** [comment]
@auxfuse I agree @ShubhamGoyal7125 This is now merged, great work!! 🥇

**Pull request merged**
