### PR TITLE
#65 : Community Contact Form & Email

### PR DESCRIPTION
**Pull request by alissatroiano**
# Community Contact Form & Email #65 

## PR contains:
- **NEW** `contact.html` file
- **UPDATED** `style.css` with:
      - Contact section styles-
- **NEW** `script.js` file - creates a fun, thematic effect so user input displays in JSON
- **NEW** `email.js` file with script & test credentials

## PR Resolves: 
#65 

## Hacktoberfest 2022:
- [x] Does this PR follow the `intermediate.md` guide and submitted as part of Hacktoberfest 2022?

## Breaking changes
- 'None'

## Screenshots

https://user-images.githubusercontent.com/56362524/194597335-d4ce675d-34f9-4e66-80a1-0367142a9c56.mov

### CODE REVIEW

**Review by auxfuse — CHANGES_REQUESTED** [review]
Hi @alissatroiano this is fantastic 🤩 Genuinely so damn good 🤜 

My only comment is that your PR seems to move the `community.json` file out to the root again? It was recently moved inside the `data` nested directory, for reference: https://github.com/auxfuse/hackathon-git-labs/tree/main/assets/data 

Can you do a `git pull upstream main` to sync your fork & branch up with the project? Once that's done, we can approve, and merge instantly! 🙌 🎉

**Review by andrewdempsey2018 — COMMENTED** [review]
Hi @alissatroiano This is just incredible! 🥇 I have tested it and it works perfectly! Did you make any changes to community.json?

**Comment by andrewdempsey2018** [comment]
@alissatroiano @auxfuse Does not appear to be the latest version of community.json just a heads up

**Comment by alissatroiano** [comment]
> Hi @alissatroiano this is fantastic 🤩 Genuinely so damn good 🤜
> 
> My only comment is that your PR seems to move the `community.json` file out to the root again? It was recently moved inside the `data` nested directory, for reference: https://github.com/auxfuse/hackathon-git-labs/tree/main/assets/data
> 
> Can you do a `git pull upstream main` to sync your fork & branch up with the project? Once that's done, we can approve, and merge instantly! 🙌 🎉

hmm, no idea how I did that lol - I'm going to pull from main again

**Review by auxfuse — APPROVED** [review]
Awesome stuff @alissatroiano Genuinely so damn good 🙌

**Comment by alissatroiano** [comment]
@auxfuse I think 

> I just pulled in from main again and deleted the extra file

**Pull request merged**
