### PR TITLE
nav bar created

### PR DESCRIPTION
**Pull request by itsBaivab**
# Hackathon Git Labs Project PR 🎉🎉

👉 _**Please remove the below and replace with your own values, leaving the headers where they are.**_ 👈

## PR contains:
- Created the nav bar and just added random placeholders links . 
- If this PR followed the `basic.md` guide, please just add your JSON Object data here and a small note about your experience following this guide.
- (don't know how to access a json file so just added the file in the community section but i think its is not working cuz, its is not showing in the web page as other cards )

## Hacktoberfest 2022:
- [ ] Does this PR follow the `intermediate.md` guide and submitted as part of Hacktoberfest 2022?
- [ ] yes i tried to follow it but guess its not working so you can clear the hacktoberfest tag from it.😕

_Please note, we cannot accept `basic.md` PR submissions for Hacktoberfest, it must be a custom HTML or CSS creation following the `intermediate.md` guide._

## Breaking changes
- IF ANYTHING YOU'RE COMMITTING WOULD BREAK SOMETHING, INCLUDE HERE WHAT WOULD BREAK
- my own code is not working don't know why in the mobile screen aspect ratio, kindly create a issue as a bug or please tell me how to do it as i spead more than 2 days working on it. As per my knowladge the 1st section id : content is somehow make a opacity issue to the the drop down navbar and making it unable to see in a certain region .

## Screenshots
- IF YOU HAVE ANY SCREENSHOTS, INCLUDE THEM HERE.
- IF YOU HAVE NO SCREENSHOTS, ENTER 'None'

### CODE REVIEW

**Review by andrewdempsey2018 — COMMENTED** [review]
@itsBaivab This is really cool!

image

I'd suggest making the link hover consistent with the other links on the home page (with the nice underline animation). As it stands, we have 'Hackathon Git Labs' written in the top left of the site twice, perhaps this could be reshaped... The burger icon could be activated and whilst the links of course cannot be activated, the home one at least could. It is a really, really good PR!!

@auxfuse Thoughts on the above, I'd like your input, shall we merge as is??

**Comment by itsBaivab** [comment]
Can you please add a hacktober fest label on it ?

**Review by andrewdempsey2018 — CHANGES_REQUESTED** [review]
Hi @itsBaivab This is an excellent PR, the navbar is excellent. However we don't feel the main site is ready right now for your navbar. We can get this merged right now but would you mind moving the navbar from the main index.html to basic.html? We would like to have your navbar on a page that is not yet live/accessible to the public so that you may work on it / improve it before moving it on over to the home page / main index.html

So, to reiterate, if you could move your navbar changes from here:

https://github.com/auxfuse/hackathon-git-labs/blob/main/index.html

to here:

https://github.com/auxfuse/hackathon-git-labs/blob/main/basic.md

Thanks again for your hard work @itsBaivab 🥇

**Comment by itsBaivab** [comment]
But that's a guide how i suppose to write html in it? 
Could you please explain a little further as I am new in this.

**Comment by auxfuse** [comment]
> But that's a guide how i suppose to write html in it? Could you please explain a little further as I am new in this.

Good morning @itsBaivab we also have the guides in html format 😄 It is in the root of the file directory (you might need to pull down the changes to your branch if you don't have `basic.html` in your file directory). I've added a snapshot of the file directory 🤜 See below:

image

**Pull request closed without merging**
