### PR TITLE
Added breakpoints

### PR DESCRIPTION
**Pull request by andrius-siup**
# Hackathon Git Labs Project PR 🎉🎉

## PR contains:
- Added breakpoints for the page.

## Hacktoberfest 2022:
- [x] Does this PR follow the `intermediate.md` guide and submitted as part of Hacktoberfest 2022?

_Please note, we cannot accept `basic.md` PR submissions for Hacktoberfest, it must be a custom HTML or CSS creation following the `intermediate.md` guide._

## Breaking changes
- None

## Screenshots
- None

### CODE REVIEW

**Review by andrewdempsey2018 — CHANGES_REQUESTED** [review]
@andrius-siup This looks really interesting 👍 could you elaborate a bit more as to what you have done here... Perhaps share a few screenshots of how the break points affect the layout of the site.

**Comment by auxfuse** [comment]
Hi @andrius-siup @andrewdempsey2018 , I've deleted that rather strange comment on this PR about attribution...😄 Thanks for being awesome you two 🤜

**Comment by andrius-siup** [comment]
Sorry guys, I added breakpoints to my single page. What I did do wrong here?

**Comment by auxfuse** [comment]
Nothing wrong @andrius-siup 🤜 and thanks for reaching out on Slack! I'm happy to approve and merge this now, and really looking forward to seeing your additions into the project. 🙌

**Comment by andrewdempsey2018** [comment]
Thanks for getting back to me Andrius

**Pull request merged**
