### PR TITLE
Add Grace to community.json

### PR DESCRIPTION
**Pull request by gracemcken**
# Hackathon Git Labs Project PR 🎉🎉

👉 _**Please remove the below and replace with your own values, leaving the headers where they are.**_ 👈

## PR contains:
- Added JSON Object following `basic.md` guide.
- {
        "name": "Grace",
        "course_start": "2022",
        "course_stage": "Student",
        "favorite_language": "JavaScript",
        "currently_learning": "Python"
    }
Nice and simple to follow.
## Hacktoberfest 2022:
- [ ] Does this PR follow the `intermediate.md` guide and submitted as part of Hacktoberfest 2022?

_Please note, we cannot accept `basic.md` PR submissions for Hacktoberfest, it must be a custom HTML or CSS creation following the `intermediate.md` guide._

## Breaking changes
- IF ANYTHING YOU'RE COMMITTING WOULD BREAK SOMETHING, INCLUDE HERE WHAT WOULD BREAK
- IF YOU HAVE NO BREAKING CHANGES, ENTER 'None'

## Screenshots
- IF YOU HAVE ANY SCREENSHOTS, INCLUDE THEM HERE.
- IF YOU HAVE NO SCREENSHOTS, ENTER 'None'

### CODE REVIEW

**Review by alissatroiano — CHANGES_REQUESTED** [review]
Great job with the `community.json` file, Grace! All you have to do now is create a fully custom directory in the `community` folder.  

Be mindful of naming conventions, as JSON is very case-sensitive (example: if your name is "Grace" in `community.json` your personal folder should also be named "Grace").  Check-out the 

custom-dir

Make sure to review the `intermediate.md` documentation, so you know what PR's will be accepted: https://github.com/auxfuse/hackathon-git-labs/blob/main/intermediate.md

Have fun and don't be afraid to get creative on that landing page!

**Comment by gracemcken** [comment]
Ah, didn't realise that needed to be done before the first PR, cheers. Done now

**Comment by alissatroiano** [comment]
> Ah, didn't realise that needed to be done before the first PR, cheers. Done now

Nice one! I believe a JS file is also needed and I'm almost positive empty files will not be approved for merge. But good work so far!

**Review by alissatroiano — CHANGES_REQUESTED** [review]
No blank files

**Comment by gracemcken** [comment]
Ah right, half asleep, I thought this was just for set up. Sorry!

**Comment by gracemcken** [comment]
Should be enough for a PR now!

Added things to PR, basic structure and layout for index.html and some CSS.

**Review by auxfuse — APPROVED** [review]
Hi Grace 👋 great to see your PR in! This looks great. We are going to merge this one, and you can create as many additional PRs later 😄🤜

**Pull request merged**
