### PR TITLE
Created accessibility.html page

### PR DESCRIPTION
**Pull request by manni8436**
# Hackathon Git Labs Project PR 🎉🎉

👉 _**Please remove the below and replace with your own values, leaving the headers where they are.**_ 👈

## PR contains:
- Created accessibility.html page.
- Styled page to match rest of site.
- Fixed two typos in privacy.html page.

## Hacktoberfest 2022:
- [x] Does this PR follow the `intermediate.md` guide and submitted as part of Hacktoberfest 2022?

_Please note, we cannot accept `basic.md` PR submissions for Hacktoberfest, it must be a custom HTML or CSS creation following the `intermediate.md` guide._

## Breaking changes
None

## Screenshots
html-screenshot

css-screenshot

website-screenshot

### CODE REVIEW

**Review by andrewdempsey2018 — APPROVED** [review]
Looks great @manni8436 nice one! 🥇

**Comment by manni8436** [comment]
Thanks so much @andrewdempsey2018 🎉☺️

**Comment by auxfuse** [comment]
Hi guys, sorry to be a stickler here...but why was the Pagination styles removed? This is a considerable block of code removed with not justification detailed in the PR template?

image

**Comment by manni8436** [comment]
Hey @auxfuse, it wasn't removed, I just moved it above the media queries, maybe I forgot to add it to the PR in the what's included section 😥, my bad

**Comment by auxfuse** [comment]
Ah perfect! If I had of done my homework I would've seen that 😆 Good stuff my man 🤜

**Comment by manni8436** [comment]
It's all good, you are Kay making sure and doing your job 🤛 😊

**Pull request merged**
